package org.grouplens.lenskit.ihm;

import org.grouplens.lenskit.hello.PalanqueExample;

/**
 * Created by anais on 26/04/16.
 */
public class Ihm extends javax.swing.JFrame {

    /**
     * Creates new form Ihm
     */
    public Ihm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUserUserCollaborativeFiltering = new javax.swing.JButton();
        jItemItemCollaborativeFiltering = new javax.swing.JButton();
        jMatrixFactorization = new javax.swing.JButton();
        jSlopeOne = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jUserUserCollaborativeFiltering.setText("User User Collaborative Filtering");
        jUserUserCollaborativeFiltering.setToolTipText("");
        jUserUserCollaborativeFiltering.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUserUserCollaborativeFilteringMouseClicked(evt);
            }
        });


        jItemItemCollaborativeFiltering.setText("Item Item Collaborative Filtering");
        jItemItemCollaborativeFiltering.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jItemItemCollaborativeFilteringMouseClicked(evt);
            }
        });

        jMatrixFactorization.setText("Matrix Factorisation");
        jMatrixFactorization.setActionCommand("Matrix Factorization");
        jMatrixFactorization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMatrixFactorizationMouseClicked(evt);
            }
        });

        jSlopeOne.setText("Slope-One");
        jSlopeOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlopeOneMouseClicked(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel1.setText("Numéro d'utilisateur :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jUserUserCollaborativeFiltering, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jItemItemCollaborativeFiltering, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jSlopeOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jMatrixFactorization, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jUserUserCollaborativeFiltering)
                                .addGap(18, 18, 18)
                                .addComponent(jItemItemCollaborativeFiltering)
                                .addGap(18, 18, 18)
                                .addComponent(jMatrixFactorization)
                                .addGap(18, 18, 18)
                                .addComponent(jSlopeOne)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String[] getSelectedParameters(String algo) {
        String num = jComboBox1.getSelectedItem().toString();
        System.out.println(num);
        String[] args = new String[2];
        args[0] = algo;
        args[1] = num;
        return args;
    }

    private void jUserUserCollaborativeFilteringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserUserCollaborativeFilteringMouseClicked
        PalanqueExample ex = new PalanqueExample(getSelectedParameters("user"));
        ex.run();
    }

    private void jItemItemCollaborativeFilteringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jItemItemCollaborativeFilteringMouseClicked
        PalanqueExample ex = new PalanqueExample(getSelectedParameters("item"));
        ex.run();
    }//GEN-LAST:event_jItemItemCollaborativeFilteringMouseClicked

    private void jMatrixFactorizationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMatrixFactorizationMouseClicked
        PalanqueExample ex = new PalanqueExample(getSelectedParameters("matrix"));
        ex.run();
    }//GEN-LAST:event_jMatrixFactorizationMouseClicked

    private void jSlopeOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlopeOneMouseClicked
        PalanqueExample ex = new PalanqueExample(getSelectedParameters("slope"));
        ex.run();
    }//GEN-LAST:event_jSlopeOneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ihm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JButton jItemItemCollaborativeFiltering;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jMatrixFactorization;
    private javax.swing.JButton jSlopeOne;
    private javax.swing.JButton jUserUserCollaborativeFiltering;
    // End of variables declaration//GEN-END:variables
}